name: Build LaTeX document
on: 
  push: 
    branches: [ main ]
    paths-ignore:
      - 'formulubladI.pdf'
      - 'formulubladII.pdf'
      - 'formulubladIIIA.pdf'
      - 'formulubladTvinn.pdf'
  workflow_dispatch:

permissions:
  contents: write   # 👈 allow pushing commits


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            formulubladI.tex
            formulubladII.tex
            formulubladIIIA.tex
            formulubladTvinn.tex
      - name: Commit PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add formulubladI.pdf formulubladII.pdf formulubladIIIA.pdf formulubladTvinn.pdf
          git commit -m "Uppfærðar pdf-skrár" || echo "No changes to commit"
          git push
